name: chemi_calc
description: "ChemiCalc — Chemical Calculator"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.5
  file_picker: ^8.0.0
  image: 4.8.0
  path_provider: 2.1.5
  google_mobile_ads: ^7.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/logo 2.png"
  image_path_ios: "assets/icons/logo 2.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A6CF0"
  adaptive_icon_foreground: "assets/icons/logo 2.png"
  remove_alpha_ios: true


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/data/
    - assets/icons/
    - assets/images/
    - assets/docs/about_us.txt
    - assets/docs/privacy_policy.txt
    - assets/docs/terms_and_conditions.txt
    - assets/docs/terms_of_use.txt

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
